version: "3.8"
services:
  backend:
    build:
      context: ./backend
    image: yourhub/servx-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
  frontend:
    build:
      context: ./frontend
    image: yourhub/servx-frontend:latest
    ports:
      - "80:80"
